name: Deploy Angular App to Azure Static Web App

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.1.0'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./supermarket-product-board-frontend-angular

      # Step 4: Build the Angular app
      - name: Build the Angular app
        run: npm run build -- --configuration=production
        working-directory: ./supermarket-product-board-frontend-angular

      # Step 5: Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "./supermarket-product-board-frontend-angular"
          output_location: "dist/supermarket-product-board-frontend-angular"
          deployment_action: 'upload'
          api_location: ""
