name: Deploy Azure Static Web App Ressource

# Trigger manually using the workflow_dispatch event
on:
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC-based authentication
  contents: read   # Required for reading the repository contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository containing the Bicep file
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Azure using OpenID Connect
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy the Bicep file to create Azure Static Web App resources
      - name: Deploy Azure Static Web App Resources
        uses: azure/CLI@v1
        with:
          azcliversion: 2.38.0
          inlineScript: |
            az deployment group create \
              --resource-group spb-prod-rg \
              --template-file supermarket-product-board-infrastructure/static-web-app.bicep \
              --parameters staticWebAppName=spb-prod-static-web-app \
